/// Flutter icons Shine
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Shine
///      fonts:
///       - asset: fonts/Shine.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Shine {
  Shine._();

  static const _kFontFam = 'Shine';
  static const _kFontPkg = null;

  static const IconData sc_icon = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
